#! python3
# WaveHeightForecast.py - Рассчитывает высоту волны на оз. Кубенском
# Вологодской области исходя из данных о направлении и скорости
# ветра введенных пользователем

import re # импорт модуля для работы с регулярными выражениями

# Исходный массив данных

waveHightData = {
    'North':    {'3-5': [0.17, 0.31],'6-8': [0.33, 0.48],
                '8-11': [0.39, 0.68], '11-14': [0.48, 0.78],
                '14-17': [0.60, 0,95], '17-21': [0.69, 1.10]},
    'Northeast':{'3-5': [0.15, 0.29],'6-8': [0.26, 0.44],
                '8-11': [0.37, 0.58], '11-14': [0.46, 0.71],
                '14-17': [0.55, 0,87], '17-21': [0.64, 1.03]},
    'East':     {'3-5': [0.19, 0.29],'6-8': [0.30, 0.46],
                '8-11': [0.43, 0.60], '11-14': [0.54, 0.73],
                '14-17': [0.66, 0,90], '17-21': [0.74, 1.04]},
    'Southeast':{'3-5': [0.24, 0.36],'6-8': [0.34, 0.50],
                '8-11': [0.45, 0.64], '11-14': [0.54, 0.75],
                '14-17': [0.67, 0,91], '17-21': [0.77, 1.06]},
    'South':    {'3-5': [0.20, 0.27],'6-8': [0.34, 0.65],
                '8-11': [0.46, 0.57], '11-14': [0.56, 0.69],
                '14-17': [0.68, 0,86], '17-21': [0.78, 1.01]},
    'Southwest':{'3-5': [0.17, 0.25],'6-8': [0.30, 0.40],
                '8-11': [0.42, 0.52], '11-14': [0.52, 0.69],
                '14-17': [0.63, 0.80], '17-21': [0.74, 0.92]},
    'West':     {'3-5': [0.20, 0.27],'6-8': [0.32, 0.42],
                '8-11': [0.44, 0.56], '11-14': [0.53, 0.67],
                '14-17': [0.64, 0,87], '17-21': [0.75, 0.96]},
    'Northwest':{'3-5': [0.25, 0.38],'6-8': [0.36, 0.54],
                '8-11': [0.48, 0.69], '11-14': [0.58, 0.83],
                '14-17': [0.77, 1.01], '17-21': [0.81, 1.18]}}
    
def directionOfTheWindInput():
    """Функция запрашивает у пользователя направление ветра и проверяет
    правильность ввода с помощью регулярного выражения"""
    windDirectionRegex = re.compile(r'^([1-8]){1}(,|\.)?( )?((?<=,|\.| )[1-8])?')
    while True:
        print('Выберите направление ветра \n(наберите на клавиатуре' +
              'соответствующую цифру или две цифры через запятную, \n'
              'например 5 или, 3,2 и нажмите клавишу \'ENTER\'\n' +
              'С(1), СВ(2), В(3), ЮВ(4), Ю(5), ЮЗ(6), З(7), СЗ(8)')
        windDirectionNumbers = str(input())
        mo = windDirectionRegex.search(windDirectionNumbers)
        if mo:
            break
    windDirectionNumbers = mo.group()
    return windDirectionNumbers

def directionOfTheWindReturn(number):
    """Функция возвращает направление ветра из словаря waveHightData"""
    windDirectionList = list(waveHightData.keys())
    windDirections = []
    windDirection1 = windDirectionList[int(number[0]) - 1]
    windDirections.append(windDirection1)
    if len(number) != 1:
        windDirection2 = windDirectionList[int(number[len(number) - 1]) - 1]    
        windDirections.append(windDirection2)                        
    return windDirections


def windSpeedInput():
    """Функция запрашивает у пользователя скорость ветра и проверяет
    правильность ввода с помощью регулярного выражения"""
    windSpeedRegex = re.compile(r'\d+-\d+')
    while True:
        print()
        print('Введите скорость ветра в формате 5-10, 7-12 и т.п., затем' +
              ' нажмите\nклавишу \'ENTER\'\n(порывы не указываются!)')
        windSpeed = str(input())
        mo = windSpeedRegex.search(windSpeed)
        if mo:
            break
    return windSpeed

def windGustsInput():
    """Функция запрашивает у пользователя порывы ветра"""
    while True:
        print()
        print('Введите порыв ветра и нажмите клавишу \'ENTER\'')
        try:
            windGusts = int(input())
            break
        except ValueError:
            print('Необходимо ввести одно число')
            continue
    return windGusts
        
    
windDirectionNumbers = directionOfTheWindInput()
windDirections = directionOfTheWindReturn(windDirectionNumbers)
print('Направления ветра: ' + str(windDirections))
windSpeed = windSpeedInput()
print('Скорость ветра: ' + windSpeed + ' м/с')
windGusts = windGustsInput()
print('Порывы ветра: ' + str(windGusts) + ' м/с')             
    
            

# TODO: Расчет выосты волны исходя из введенных данных
# TODO: Вывод результата
